import type { Metadata } from "next";
import "../styles/globals.css";
import { fontInter } from "@/styles/fonts";

export const metadata: Metadata = {
  title: {
    template: '%s | UrbanElegance',
    default: 'UrbanElegance',
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontInter.className} antialiased`}>{children}</body>
    </html>
  );
}
