name: Auto PR from Feature to Staging

on:
  push:
    branches:
      - feature

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Automatic PR: Update from Feature'
          branch: staging
          title: 'Automatic PR: Update from Feature'
          body: |
            This pull request was created automatically from feature branch to staging.
          labels: automatic-pr
          reviewers: ''
